// Generated by CoffeeScript 1.3.3
(function() {
  var AbstractBody, AbstractGame, AbstractPlayer, UUID, V, cardinals, diagonals, frame_rate, _;

  V = require('./server_box2d_vector').V;

  frame_rate = require('./frame_rate');

  _ = require('underscore');

  UUID = require('./library/uuid').UUID;

  cardinals = {
    left: V(-1, 0),
    right: V(1, 0),
    up: V(0, 1),
    down: V(0, -1)
  };

  diagonals = [V(1, 1), V(1, -1), V(-1, -1), V(-1, 1)];

  AbstractBody = (function() {

    function AbstractBody(game, id) {
      this.game = game;
      this.id = id != null ? id : UUID();
      this.game.bodies[this.id] = this;
      this.setup();
    }

    AbstractBody.prototype.toJSON = function() {
      return {
        id: this.id,
        position: this.body.GetPosition(),
        angle: this.body.GetAngle()
      };
    };

    AbstractBody.prototype.force = function(vector, position) {
      if (position == null) {
        position = this.body.GetPosition();
      }
      return this.body.ApplyForce(vector, position);
    };

    AbstractBody.prototype.changes = function() {
      return {
        id: this.id,
        position: this.body.GetPosition(),
        angle: this.body.GetAngle()
      };
    };

    AbstractBody.prototype.remove = function() {
      this.game.world.DestroyBody(this.body);
      return delete this.game.bodies[this.id];
    };

    return AbstractBody;

  })();

  AbstractPlayer = (function() {

    function AbstractPlayer(game, user, id) {
      this.game = game;
      this.user = user;
      this.id = id != null ? id : UUID();
      this.clear_commands();
      this.game.players[this.id] = this;
      this.user.player = this;
      this.name = this.id;
      this.setup();
    }

    AbstractPlayer.prototype.press = function(command) {
      return this.commands[command] = true;
    };

    AbstractPlayer.prototype.release = function(command) {
      return delete this.commands[command];
    };

    AbstractPlayer.prototype.clear_commands = function() {
      return this.commands = {};
    };

    AbstractPlayer.prototype.remove = function() {
      delete players[this.id];
      return this.body.remove();
    };

    return AbstractPlayer;

  })();

  AbstractGame = (function() {

    function AbstractGame(sockets, id) {
      this.sockets = sockets;
      this.id = id != null ? id : UUID();
      _.bindAll(this, 'step');
      this.channel = "game-" + this.id;
      this.players = {};
      this.bodies = {};
      this.setup();
      this.start();
    }

    AbstractGame.prototype.start = function() {
      return this.timer = setInterval(this.step, frame_rate.frame_length_milliseconds);
    };

    AbstractGame.prototype.step = function() {
      var body, changes, id, player, _ref;
      _ref = this.players;
      for (id in _ref) {
        player = _ref[id];
        player.control();
      }
      this.world.Step(frame_rate.frame_length_seconds, 10, 10);
      this.world.ClearForces();
      changes = (function() {
        var _ref1, _results;
        _ref1 = this.bodies;
        _results = [];
        for (id in _ref1) {
          body = _ref1[id];
          if (body.body.IsAwake()) {
            _results.push(body.changes());
          }
        }
        return _results;
      }).call(this);
      return this.sockets["in"](this.channel).volatile.emit('update', changes);
    };

    AbstractGame.prototype.toJSON = function() {
      return {
        id: this.id,
        things: this.bodies
      };
    };

    AbstractGame.prototype.remove = function() {
      clearTimeout(this.timer);
      return delete games[this.id];
    };

    return AbstractGame;

  })();

  exports.cardinals = cardinals;

  exports.diagonals = diagonals;

  exports.AbstractBody = AbstractBody;

  exports.AbstractPlayer = AbstractPlayer;

  exports.AbstractGame = AbstractGame;

}).call(this);
