// Generated by CoffeeScript 1.3.3
(function() {
  var deviation_history, frame_delta, get_average_deviation, get_frame_delta, last_frame_time, now;

  now = function() {
    return (new Date).valueOf();
  };

  last_frame_time = null;

  frame_delta = null;

  deviation_history = [];

  get_frame_delta = function() {
    var this_frame_time;
    this_frame_time = now();
    frame_delta = this_frame_time - last_frame_time;
    last_frame_time = this_frame_time;
    return frame_delta;
  };

  get_average_deviation = function(norm) {
    var delta, sum, value, _i, _len, _ref;
    delta = get_frame_delta(norm);
    deviation_history.push(Math.abs(norm - frame_delta));
    sum = 0;
    _ref = deviation_history.slice(-20);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      value = _ref[_i];
      sum += value;
    }
    return sum / deviation_history.length;
  };

  if (typeof exports === 'object') {
    exports.get_frame_delta = get_frame_delta;
    exports.get_average_deviation = get_average_deviation;
  } else {
    window.get_frame_delta = get_frame_delta;
    window.get_average_deviation = get_average_deviation;
  }

}).call(this);
