// Generated by CoffeeScript 1.3.3
(function() {
  var get_frame_delta, last_frame_time, now;

  now = function() {
    return (new Date).valueOf();
  };

  last_frame_time = null;

  get_frame_delta = function() {
    var frame_delta, this_frame_time;
    this_frame_time = now();
    frame_delta = this_frame_time - last_frame_time;
    last_frame_time = this_frame_time;
    return frame_delta;
  };

  if (typeof exports === 'object') {
    exports.get_frame_delta = get_frame_delta;
  } else {
    window.get_frame_delta = get_frame_delta;
  }

}).call(this);
