// Generated by CoffeeScript 1.3.3
(function() {
  var V, b2d, box_body_def, box_fixture_def, box_shape_def, box_size, gravity, server, world;

  server = require('server');

  b2d = require('box2dnode');

  V = require('./server_box2d_vector').V;

  gravity = V(0, 0);

  world = new b2d.b2World(gravity, true);

  box_size = V(2, 2);

  box_body_def = new b2d.b2BodyDef;

  box_body_def.type = b2d.b2Body.b2_dynamicBody;

  box_shape_def = new b2d.b2CircleShape;

  box_shape_def.m_radius = 1;

  box_fixture_def = new b2d.b2FixtureDef;

  box_fixture_def.shape = box_shape_def;

  box_fixture_def.density = 1.0;

  box_fixture_def.friction = 0.3;

  box_body_def.linearDamping = 1;

}).call(this);
