// Generated by CoffeeScript 1.3.3
(function() {
  var V, Vector, b2d, radians_factor;

  radians_factor = Math.PI / 180.0;

  b2d = require('box2dnode');

  Vector = b2d.b2Vec2;

  Vector.prototype.components = function() {
    return [this.x, this.y];
  };

  Vector.prototype.scale = function(scalar) {
    return new Vector(this.x * scalar, this.y * scalar);
  };

  Vector.prototype.Scale = function(scalar) {
    this.x *= scalar;
    return this.y *= scalar;
  };

  Vector.prototype.add = function(other) {
    var v;
    v = this.Copy();
    v.Add(other);
    return v;
  };

  Vector.prototype.subtract = function(other) {
    var v;
    v = this.Copy();
    v.Subtract(other);
    return v;
  };

  Vector.prototype.Rotate = function(angle) {
    return this.MulM(new b2d.b2Mat22(angle));
  };

  Vector.prototype.rotate = function(angle) {
    var v;
    v = this.Copy();
    v.Rotate(angle);
    return v;
  };

  Vector.prototype.minus = Vector.prototype.subtract;

  Vector.prototype.plus = Vector.prototype.add;

  V = function() {
    return (function(func, args, ctor) {
      ctor.prototype = func.prototype;
      var child = new ctor, result = func.apply(child, args), t = typeof result;
      return t == "object" || t == "function" ? result || child : child;
    })(Vector, arguments, function(){});
  };

  exports.V = V;

  exports.radians_factor = radians_factor;

  exports.Vector = Vector;

}).call(this);
